# Директории
lib.dir=lib
lib.test.dir=lib/test
src.dir=src/main/java
src.alt.dir=alt/main/java
src.test.dir=src/test/java
web.dir=src/main/webapp
web.alt.dir=alt/main/webapp
build.dir=build/classes
dist.dir=build/dist

# Название
app.name=itmo-web-lab-3

# Совместимость Java
source.compatibility=1.8
target.compatibility=1.8
