// Generated by delombok at Sat Dec 07 23:19:57 MSK 2024
package com.tplaymeow.itmoweblab3.Models;

public class Coordinates {
    private Double x;
    private Double y;
    private Integer r;

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Double getX() {
        return this.x;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Double getY() {
        return this.y;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Integer getR() {
        return this.r;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setX(final Double x) {
        this.x = x;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setY(final Double y) {
        this.y = y;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public void setR(final Integer r) {
        this.r = r;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Coordinates)) return false;
        final Coordinates other = (Coordinates) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$x = this.getX();
        final java.lang.Object other$x = other.getX();
        if (this$x == null ? other$x != null : !this$x.equals(other$x)) return false;
        final java.lang.Object this$y = this.getY();
        final java.lang.Object other$y = other.getY();
        if (this$y == null ? other$y != null : !this$y.equals(other$y)) return false;
        final java.lang.Object this$r = this.getR();
        final java.lang.Object other$r = other.getR();
        if (this$r == null ? other$r != null : !this$r.equals(other$r)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Coordinates;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $x = this.getX();
        result = result * PRIME + ($x == null ? 43 : $x.hashCode());
        final java.lang.Object $y = this.getY();
        result = result * PRIME + ($y == null ? 43 : $y.hashCode());
        final java.lang.Object $r = this.getR();
        result = result * PRIME + ($r == null ? 43 : $r.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public java.lang.String toString() {
        return "Coordinates(x=" + this.getX() + ", y=" + this.getY() + ", r=" + this.getR() + ")";
    }

    @java.lang.SuppressWarnings("all")
    @lombok.Generated
    public Coordinates(final Double x, final Double y, final Integer r) {
        this.x = x;
        this.y = y;
        this.r = r;
    }
}
